# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\"\\\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\"\x8e\x01\n\x10RegisterResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x12\n\nerror_code\x18\x07 \x01(\x05\x12\x0f\n\x07message\x18\x08 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x8b\x01\n\rLoginResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x12\n\nerror_code\x18\x07 \x01(\x05\x12\x0f\n\x07message\x18\x08 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x0eLogoutResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2\x90\x01\n\x04\x41uth\x12(\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12\x31\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\"\x00\x12+\n\x06Logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\"\x00\x42\x39Z7github.com/AppsLab-KE/backend-everyshillings-proto/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/AppsLab-KE/backend-everyshillings-proto/auth'
  _REGISTERREQUEST._serialized_start=19
  _REGISTERREQUEST._serialized_end=111
  _REGISTERRESPONSE._serialized_start=114
  _REGISTERRESPONSE._serialized_end=256
  _LOGINREQUEST._serialized_start=258
  _LOGINREQUEST._serialized_end=305
  _LOGINRESPONSE._serialized_start=308
  _LOGINRESPONSE._serialized_end=447
  _LOGOUTREQUEST._serialized_start=449
  _LOGOUTREQUEST._serialized_end=479
  _LOGOUTRESPONSE._serialized_start=481
  _LOGOUTRESPONSE._serialized_end=512
  _AUTH._serialized_start=515
  _AUTH._serialized_end=659
# @@protoc_insertion_point(module_scope)
