# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\".\n\x0b\x43redentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"C\n\rLoginResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\x05\x32-\n\x04\x41uth\x12%\n\x05Login\x12\x0c.Credentials\x1a\x0e.LoginResponseB9Z7github.com/AppsLab-KE/backend-everyshillings-proto/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/AppsLab-KE/backend-everyshillings-proto/auth'
  _CREDENTIALS._serialized_start=19
  _CREDENTIALS._serialized_end=65
  _LOGINRESPONSE._serialized_start=67
  _LOGINRESPONSE._serialized_end=134
  _AUTH._serialized_start=136
  _AUTH._serialized_end=181
# @@protoc_insertion_point(module_scope)
