// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: otp/otp.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAndSendOtpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	OtpLength   string `protobuf:"bytes,2,opt,name=otp_length,json=otpLength,proto3" json:"otp_length,omitempty"`
}

func (x *CreateAndSendOtpReq) Reset() {
	*x = CreateAndSendOtpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otp_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAndSendOtpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAndSendOtpReq) ProtoMessage() {}

func (x *CreateAndSendOtpReq) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAndSendOtpReq.ProtoReflect.Descriptor instead.
func (*CreateAndSendOtpReq) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAndSendOtpReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateAndSendOtpReq) GetOtpLength() string {
	if x != nil {
		return x.OtpLength
	}
	return ""
}

var File_otp_otp_proto protoreflect.FileDescriptor

var file_otp_otp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x74, 0x70, 0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6f, 0x74, 0x70, 0x22, 0x57, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x64, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x74, 0x70, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x74, 0x70, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x70, 0x70, 0x73,
	0x4c, 0x61, 0x62, 0x2d, 0x4b, 0x45, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x65,
	0x76, 0x65, 0x72, 0x79, 0x73, 0x68, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x6f, 0x74,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otp_otp_proto_rawDescOnce sync.Once
	file_otp_otp_proto_rawDescData = file_otp_otp_proto_rawDesc
)

func file_otp_otp_proto_rawDescGZIP() []byte {
	file_otp_otp_proto_rawDescOnce.Do(func() {
		file_otp_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_otp_otp_proto_rawDescData)
	})
	return file_otp_otp_proto_rawDescData
}

var file_otp_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_otp_otp_proto_goTypes = []interface{}{
	(*CreateAndSendOtpReq)(nil), // 0: otp.CreateAndSendOtpReq
}
var file_otp_otp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_otp_otp_proto_init() }
func file_otp_otp_proto_init() {
	if File_otp_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_otp_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAndSendOtpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otp_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otp_otp_proto_goTypes,
		DependencyIndexes: file_otp_otp_proto_depIdxs,
		MessageInfos:      file_otp_otp_proto_msgTypes,
	}.Build()
	File_otp_otp_proto = out.File
	file_otp_otp_proto_rawDesc = nil
	file_otp_otp_proto_goTypes = nil
	file_otp_otp_proto_depIdxs = nil
}
